---
title: "Coho Abundance Figures"
author: "Peter et al."
date: "2025-01-23"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 10, fig.height = 7.5)
library(tidyverse)
library(ggpubr)
library(DT)
library(htmltools)
library(plotly)
# library(CCA)
# library(CCP)
library(readxl)
library(paletteer)

# data.frame() %>%
#   DT::datatable() %>%
#   knitr::knit_print() %>%
#   attr('knit_meta') %>%
#   knitr::knit_meta_add() %>%
#   invisible()
```

```{r copy_data_over}
if(stringr::str_detect(getwd(),"CMADSEN")){
  file.copy(
    from = "C:/Users/CMADSEN/Downloads/LocalR/long_term_projects/CarnationCreekDataCleaning/outputs/data_adult_spawners.xlsx",
    to = "C:/Users/CMADSEN/Downloads/LocalR/long_term_projects/CarnationCreek/data/data_adult_spawners.xlsx"
  )
  file.copy(
    from = "C:/Users/CMADSEN/Downloads/LocalR/long_term_projects/CarnationCreekDataCleaning/outputs/data_agescale_1991-2019.xlsx",
    to = "C:/Users/CMADSEN/Downloads/LocalR/long_term_projects/CarnationCreek/data/data_agescale.xlsx"
  )
  file.copy(
    from = "C:/Users/CMADSEN/Downloads/LocalR/long_term_projects/CarnationCreekDataCleaning/outputs/data_outmigration_1991-2023.xlsx",
    to = "C:/Users/CMADSEN/Downloads/LocalR/long_term_projects/CarnationCreek/data/data_outmigration_1991-2023.xlsx"
  )
}
```

```{r load_in_data}
# Load in formatted datasets
#hyd = read_csv("data/formatted/all_hydro_data_by_year.csv")
spawners = readxl::read_excel("data/data_adult_spawners.xlsx")

juv_co = readxl::read_excel(paste0("data/raw/fish_data/late_summer_juv_coho_pop_ests_by_section.xlsx")) |> 
  purrr::set_names(snakecase::to_snake_case) |> 
  dplyr::arrange(year) |> 
  dplyr::mutate(population_estimate_n = as.numeric(population_estimate_n))

co = readxl::read_excel(paste0("data/raw/fish_data/overwinter_survival.xlsx")) |> 
  purrr::set_names(snakecase::to_snake_case) |> 
  dplyr::arrange(year) |> 
  dplyr::mutate(late_summer_coho_population_abundance = as.numeric(late_summer_coho_population_abundance),
                smolt_abundance = as.numeric(smolt_abundance)) |> 
  dplyr::select(-logging_phase)

co_section = readxl::read_excel(paste0("data/raw/fish_data/multiyear_summary_late_summer_coho_pops.xlsx")) |> 
  purrr::set_names(snakecase::to_snake_case) |> 
  tidyr::pivot_longer(-c(year,comments))

logging_phases = data.frame(
  year = c(1971:1975, 1976:1981, 1982:1994, 1995:2025),
  logging_phase = c(rep("pre_logging",1975-1970),rep("during_logging",1981-1975),rep("post_logging_1",1994-1981),rep("post_logging_2",2025-1994))
)

co = co |> 
  dplyr::left_join(logging_phases) |> 
  dplyr::mutate(logging_phase = factor(logging_phase, levels = c("pre_logging","during_logging","post_logging_1","post_logging_2")))

juv_co = juv_co |> 
  dplyr::left_join(logging_phases) |> 
  dplyr::mutate(logging_phase = factor(logging_phase, levels = c("pre_logging","during_logging","post_logging_1","post_logging_2")))

juv_co = juv_co |> 
  dplyr::mutate(section = paste0("Section ",section))

juv_co = juv_co |> 
  dplyr::mutate(logging_colour = dplyr::case_when(
    logging_phase == "pre_logging" ~ "#e09a5c",
    logging_phase == "during_logging" ~ "#c1e05c",
    logging_phase == "post_logging_1" ~ "#25ab99",
    logging_phase == "post_logging_2" ~ "#7c3bbc"
  ))

juv_co_s = juv_co |> dplyr::group_by(year,logging_phase,logging_colour) |> dplyr::reframe(population_estimate_n = sum(population_estimate_n,na.rm=T))

co = co |> 
  dplyr::mutate(logging_colour = dplyr::case_when(
    logging_phase == "pre_logging" ~ "#e1c1a4",
    logging_phase == "during_logging" ~ "#d9e4b6",
    logging_phase == "post_logging_1" ~ "#9ac1bc",
    logging_phase == "post_logging_2" ~ "#b4a2c5"
  ))

co_colour_values = co |> 
  dplyr::select(logging_phase, logging_colour) |> 
  dplyr::distinct() |> 
  dplyr::reframe(values = paste0("'",logging_phase,"' = '",logging_colour,"'"))

juv_co_colour_values = juv_co |> 
  dplyr::select(logging_phase, logging_colour) |> 
  dplyr::distinct() |> 
  dplyr::reframe(values = paste0("'",logging_phase,"' = '",logging_colour,"'"))

coho_colour_values = dplyr::bind_rows(
  co_colour_values,
  juv_co_colour_values
)

my_comparisons <- list( c("pre_logging", "during_logging"), 
                        c("pre_logging", "post_logging_1"), 
                        c("pre_logging", "post_logging_2"),
                        c("during_logging","post_logging_1",
                          "during_logging","post_logging_2",
                          "post_logging_1","post_logging_2"))
```

# Carnation Creek Plots {.tabset}

## Barplots {.tabset}

### Coho Pop by Year and Logging Phase

```{r, fig.height=6}
co |> 
  ggplot() + 
  geom_col(aes(x = year, y = late_summer_coho_population_abundance, fill = logging_phase)) +
  # facet_wrap(~ section, ncol = 1) +
  scale_fill_paletteer_d("nationalparkcolors::Badlands") + 
  labs(y = "Late Summer Coho Population Estimate", x = "Year and Logging Phase", fill = "Logging Phase") +
  ggthemes::theme_pander()

```

### Coho Pop and Smolt Abundance by Year and Logging Phase

```{r fig.height=6}

logging_changes = data.frame(
  Year = c(1975.5,1981.5,1995.5)
)

logging_phase_labels = data.frame(
  Year = c(1972, 1978.5, 1988, 2013),
  label = c("Pre","During","Post 1","Post 2"),
  color = c("limegreen","gold","orange","darkred")
)

# fish = dplyr::bind_rows(co |> 
#                           mutate(dattype = 'late_summer_abund') |> 
#                           rename(population_estimate_n = late_summer_coho_population_abundance), 
#                         juv_co_s |> mutate(dattype = 'juveniles'))

ggplot()+
  geom_col(aes(x = year, y = late_summer_coho_population_abundance, fill = 'juveniles'),alpha=0.8, data = co) +
  geom_col(aes(x = year, y = population_estimate_n, fill = 'smolts'), alpha=0.8, data = juv_co_s) + 
  scale_fill_paletteer_d("nationalparkcolors::Badlands") +
  # scale_fill_manual(values = c(coho_colour_values$values))
  # scale_fill_identity(guide = "legend") + 
  geom_vline(data = logging_changes, aes(xintercept = Year), lty = 1, alpha = 0.5, color = 'darkred') +
  geom_text(data =logging_phase_labels, aes(x = Year, y = 24000, label = label), alpha = 0.3) + 
  labs(fill = 'Fish Age', y = 'population estimate (N)', x = 'Year and Logging Phase') +
  ggthemes::theme_pander()

ggplot()+
  geom_col(aes(x = year, y = late_summer_coho_population_abundance, fill = 'juveniles'),alpha=0.8, data = co) +
  geom_col(aes(x = year, y = population_estimate_n, fill = 'smolts'), alpha=0.8, data = juv_co_s) + 
  scale_fill_paletteer_d("nationalparkcolors::Badlands") +
  # scale_fill_manual(values = c(coho_colour_values$values))
  # scale_fill_identity(guide = "legend") + 
  geom_vline(data = logging_changes, aes(xintercept = Year), lty = 1, alpha = 0.5, color = 'darkred') +
  geom_text(data =logging_phase_labels, aes(x = Year, y = 24000, label = label), color = logging_phase_labels$color) + 
  labs(fill = 'Fish Age', y = 'population estimate (N)', x = 'Year and Logging Phase') +
  ggthemes::theme_pander()
```

### Coho Pop by Year and Logging Phase by Section

```{r}
co_section |> 
  dplyr::left_join(logging_phases) |> 
  ggplot() + 
  geom_col(aes(x = year, y = value, fill = logging_phase)) +
  facet_wrap(~ name, ncol = 1) +
  scale_fill_paletteer_d("nationalparkcolors::Badlands") + 
  labs(y = "Late Summer Coho Population Estimate", x = "Year", fill = "Logging Phase") +
  ggthemes::theme_pander()
```

### Overwinter Survival

```{r}
ggplot() +
  geom_col(aes(x = year, y = percent_overwinter_survival), data = co) +
  scale_fill_paletteer_d("nationalparkcolors::Badlands") +
  geom_vline(data = logging_changes, aes(xintercept = Year), lty = 1, alpha = 0.5, color = 'darkred') +
  geom_text(data =logging_phase_labels, aes(x = Year, y = 1.1*max(co$percent_overwinter_survival,na.rm=T), label = label), alpha = 0.3) + 
  labs(fill = 'Fish Age', y = 'population estimate (N)', x = 'Year and Logging Phase') +
  ggthemes::theme_pander()
```

### Number of Female Spawners and Smolts per Year
```{r}
# Summarise female spawners by year and sample location
sp_y_loc = spawners |> 
  filter(sex == 'female') |> 
  count(year,sample_location,name = "female_spawners")

sp_y = spawners |> 
  filter(sex == 'female') |> 
  count(year,name = "female_spawners") |> 
  mutate(year = as.numeric(year))

ggplot()+
  geom_col(aes(x = year, y = population_estimate_n, fill = 'smolts'), alpha=0.8, data = juv_co_s) +
  geom_col(aes(x = year, y = female_spawners, fill = 'ratio'), alpha=0.8, data = sp_y) + 
  scale_fill_paletteer_d("nationalparkcolors::Badlands") +
  geom_vline(data = logging_changes, aes(xintercept = Year), lty = 1, alpha = 0.5, color = 'darkred') +
  geom_text(data =logging_phase_labels, aes(x = Year, y = 1.1*max(juv_co_s$population_estimate_n,na.rm=T), label = label), color = logging_phase_labels$color) + 
  labs(fill = 'Female Spawners', y = 'Female Spawners by Year', x = 'Year and Logging Phase') +
  ggthemes::theme_pander()
```

### Ratio of Smolts to Female Spawners by Year
```{r}
# Join spawners to smolts
juv_co_w_spawners = juv_co_s |> 
  left_join(sp_y) |> 
  mutate(smolt_to_female_spawner_ratio = population_estimate_n / female_spawners)

ggplot()+
  geom_col(aes(x = year, y = smolt_to_female_spawner_ratio, fill = 'ratio'), alpha=0.8, data = juv_co_w_spawners) + 
  scale_fill_paletteer_d("nationalparkcolors::Badlands") +
  # scale_fill_manual(values = c(coho_colour_values$values))
  # scale_fill_identity(guide = "legend") + 
  geom_vline(data = logging_changes, aes(xintercept = Year), lty = 1, alpha = 0.5, color = 'darkred') +
  geom_text(data =logging_phase_labels, aes(x = Year, y = 1.1*max(juv_co_w_spawners$smolt_to_female_spawner_ratio,na.rm=T), label = label), color = logging_phase_labels$color) + 
  labs(fill = 'Smolt:Female \nSpawner Ratio', y = 'Smolt population / Female Spawners', x = 'Year and Logging Phase') +
  ggthemes::theme_pander()
```

## Boxplots {.tabset}

### Coho Pop by Year and Logging Phase by Section

```{r}
co_section |> 
  dplyr::left_join(logging_phases) |> 
  ggplot(aes(x = logging_phase, y = value, fill = logging_phase)) + 
  geom_boxplot() + 
  facet_wrap( ~ name) +
  scale_fill_paletteer_d("nationalparkcolors::Badlands") +
  ggpubr::stat_compare_means(comparisons = my_comparisons) +
  ggpubr::stat_compare_means(method = "anova", label.y = 1000, label.x = "during_logging") +
  labs(y = "Late Summer Coho Population Estimate", x = "Year", fill = "Logging Phase") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12)) +
  ggthemes::theme_pander()
```



